.TH wscat 8 "February 15th, 2020" 0.24
.SH NAME
wscat \- write to and read from websocket
.SH SYNOPSIS
.SP
.B wscat
[OPTIONS] [URI]
.SH DESCRIPTION
The
.B wscat
command writes to and reads from a remote system via websocket protocol RFC 6455. It reads from standard input and writes to standard output. The command can be used interactively and non-interactively.
.SH OPTIONS
.TP
.IP "-A, --user-agent"
Sets User-Agent string in HTTP upgrade request. The default value is \fBwscat\fR.
.TP
.IP "-V, --sec-ws-ver"
Sets Sec-WebSocket-Version string in HTTP upgrade request. The default value is \fB13\fR.
.TP
.IP "-P, --sec-ws-proto"
Sets Sec-WebSocket-Protocol string in HTTP upgrade request. By default this string is omitted.
.TP
.IP "-K, --sec-ws-key"
Sets Sec-WebSocket-Key string in HTTP upgrade request. By default wscat calculates a pseudo-random value.
.TP
.IP "-i, --idle-timeout"
The maximum time in milliseconds that you allow wscat to idle after a read from or write to websocket, or standard input. By default the command does not timeout.
.TP
.IP "-j, --json"
Assumes that input is formatted as JavaScript Object Notation (JSON). Each object is sent in a single frame.
.TP
.IP "-N, --no-handshake"
Does not start or finish a closing handshake. Use this option to test only, it violates RFC 6455.
.TP
.IP "-R, --repeat-last"
Repeats last input as many times as specified. The last input is the input that was entered immediately before standard input was closed.
.TP
.IP "-v, --verbose"
Enables diagnostic information on standard error. Use this option multiple times for maximum effect.
.TP
.IP "-x, --no-check-certificate"
Does not check a server's certificate against available certificate authorities and does not verify that a hostname matches a common name presented by the certificate. Use this option only if you do not care about a server's authenticity.
.TP
.IP "-h, --help"
Displays help and exits.
.SH USAGE
.B wscat
expects a Uniform Resource Identifier (URI) for the remote system as defined in RFC 3986. For example, if the remote system offers a plaintext websocket on port 80 then use:

.EX
wscat ws://example.com
.EE

If on the other hand the remote system offers an encrypted websocket on port 443 then use:

.EX
wscat wss://example.com
.EE

If a websocket in either case is offered on a non-standard port then
.B wscat
can be told so by appending the port number:

.EX
wscat ws://example:1234
.EE

.B wscat
can only communicate with an encrypted websocket if your site has a resonably recent version of OpenSSL library installed. If no URI is specified at all then the command assumes a plaintext websocket at port 80 on localhost.
.SH BUGS
Please report to bugs@sequencedsystems.com.
.SH "SEE ALSO"
.BR wsd (8)
