.TH wsd 8 "January 4th, 2017" 0.13
.SH NAME
wsd \- high performance websocket proxy
.SH SYNOPSIS
.SP
.B wsd
[OPTIONS]
.SH DESCRIPTION
The
.B wsd
websocket proxy is a high performance daemon that implements a practical subset of the websocket protocol as defined by RFC 6455. It uses epoll(7) to multiplex concurrent network connections, minimises memory copies and avoids allocating memory at runtime whenever possible. 
.SH OPTIONS
.TP
.BI \-h " host"
Proxies websocket connections to host. Default is 127.0.0.1.
.TP
.BI \-f " port"
Proxies websocket connections to port. Default is 6085.
.TP
.BI \-o " port"
Listens on port for incoming connections. Default is 6084.
.TP
.BI \-p " file"
Stores process id in file.
.TP
.BI \-u " user"
Runs daemon as user. Default is \fBwsd\fR; user cannot be root.
.TP
.B \-d
Does not fork and stays attached to terminal.
.TP
.B \-v
Logs to stdout, use option multiple times for more detail.
.SH BUGS
Please report to bugs@sequencedsystems.com.
