.TH wsd 8 "July 10th, 2018" 0.23
.SH NAME
wsd \- terminate websockets and multiplex to remote host
.SH SYNOPSIS
.SP
.B wsd
[OPTIONS]
.SH DESCRIPTION
The
.B wsd
daemon terminates websockets and multiplexes their frames to some backend using proxy protocol 2 (PP2). At the websocket interface, it implements a practical subset of the websocket protocol as defined by RFC 6455. It is designed to be reasonably fast by minimising system calls, memory copying and runtime memory allocation. 
.SH OPTIONS
.TP
.BI \-h " host"
Multiplexes websocket frames to some host. Default is 127.0.0.1.
.TP
.BI \-f " port"
Multiplexes websocket frames to a port. Default is 6085.
.TP
.BI \-o " port"
Listens on port for incoming websocket connections. Default is 6084.
.TP
.BI \-p " file"
Stores process id in file.
.TP
.BI \-u " user"
Runs daemon as user. Default is \fBwsd\fR; user cannot be root.
.TP
.B \-d
Does not fork and stays attached to terminal.
.TP
.B \-i
Sets idle read/write timeout in milliseconds. This is the maximum time that you allow a websocket to idle after a read from or a write to it. Default is 30 seconds.
.TP
.B \-v
Enables diagnostic information on standard error. Use this option multiple times for maximum effect. Implies that daemon stays attached to terminal.
.TP
.B \-?
Displays help and exits.
.SH BUGS
Please report to bugs@sequencedsystems.com.
.SH "SEE ALSO"
.BR wscat (8)
